project_name: "sensu-pingdom-checks"
builds:
  # List of builds
  - main: ./cmd/check-pingdom-aggregates/
    id: "check-pingdom-aggregates"
    env:
    - CGO_ENABLED=0
    ldflags: '-s -w -X github.com/sensu-community/sensu-plugin-sdk/version.version={{.Version}} -X github.com/sensu-community/sensu-plugin-sdk/version.commit={{.Commit}} -X github.com/sensu-community/sensu-plugin-sdk/version.date={{.Date}}'
    binary: bin/check-pingdom-aggregates
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    targets:
      - darwin_amd64
      - linux_386
      - linux_amd64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64
      - windows_386
      - windows_amd64

  - main: ./cmd/check-pingdom-credits
    id: "check-pingdom-credits"
    env:
    - CGO_ENABLED=0
    ldflags: '-s -w -X github.com/sensu-community/sensu-plugin-sdk/version.version={{.Version}} -X github.com/sensu-community/sensu-plugin-sdk/version.commit={{.Commit}} -X github.com/sensu-community/sensu-plugin-sdk/version.date={{.Date}}'
    binary: bin/check-pingdom-credits
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    targets:
      - darwin_amd64
      - linux_386
      - linux_amd64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64
      - windows_386
      - windows_amd64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
